server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
  #servlet:
    #context-path: /car-rental/api


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carrental_db
    username: carrentaluser
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

greenrent:
  app:
    jwtSecret: greenRent@12
    jwtExpirationMs: 86400000

logging:
  file:
    name: logs/greenrent.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"

  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO
    '[com.greenrent]': DEBUG

info:
  application:
    name: 'GreenRent Backend App.'
    descprition: 'This is GreenRent Backend app dev by GreenRent Dev Team'
    version: '@project.version@'